### ISSUE TITLE
Cannot start the app

### ISSUE THREAD

**Issue by lightonflux** [flathub/uk.et1.big-finish-downloader#1]
Just installed the app, and i cannot start it. 

```» flatpak run uk.et1.big-finish-downloader 
Log init failed: logger with name 'log' already exists```

**Comment by Emersont1** [comment]
Hi, should be fixed in v1.0.2

**Comment by Emersont1** [comment]
Should be able run if you update with `flatpak update`

**Comment by lightonflux** [comment]
Updated. Can confirm. It now starts and displays the login window.

Thanks for the fast response!
