### ISSUE TITLE
No .desktop starter is created

### ISSUE THREAD

**Issue by lightonflux** [flathub/uk.et1.big-finish-downloader#2]
I installed the app on Fedora 33. The OS is fully updated and flatpak is version `1.10.1`.

With `menulibre` i checked if a starter was create, but couldn't find one. If a starter is created, but the executable is missing or similar issues it will be hidden in the menu/application listing.

**Comment by Emersont1** [comment]
I think this is due to it not being named correctly when installed, however I need to test this

**Comment by Emersont1** [comment]
Right, it turns out the `TryExec` line in the desktop doesn't work, so I added an `Exec` line, which now works, I'll push out a version 1.0.3 as soon as the CI is done

**Comment by lightonflux** [comment]
Explanation of TryExec (with links to documentation): https://unix.stackexchange.com/a/309323

(Just because i was curious.)

**Comment by Emersont1** [comment]
Ah, that makes sense, still, its been fixed now
