### ISSUE TITLE
Use xdg-dirs

### ISSUE THREAD

**Issue by lightonflux** [flathub/uk.et1.big-finish-downloader#4]
My locale is de_DE, so the app created a folder called Music instead of using Musik. The app should follow the xdg spec for user directories:

See ~/.config/user-dirs.dirs and the [specification](https://freedesktop.org/wiki/Software/xdg-user-dirs/).

**Comment by Emersont1** [comment]
fixed by Emersont1/big-finish-downloader#34

will go live with the 1.1 release
